- name: Criando Grupo de Segurança
  amazon.aws.ec2_security_group:
    name: '{{ security_group_name }}'
    region: '{{ region }}'
    description: Libera o acesso para as portas necessarias para Topologia da Rede
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    aws_session_token: '{{ aws_session_token }}'
    rules:
      - proto: tcp
        ports:
        - '80'
        cidr_ip: 0.0.0.0/0
        rule_desc: Porta para acesso HTTP liberado
      - proto: tcp
        ports:
        - '22'
        cidr_ip: 0.0.0.0/0
        rule_desc: Porta para acesso SSH liberado
      - proto: tcp
        ports:
        - '9000'
        cidr_ip: 0.0.0.0/0
        rule_desc: Porta para acesso do Terminal Web

- name: Criando par de chaves
  amazon.aws.ec2_key:
    name: '{{ key_name }}'
    region: '{{ region }}'
    key_type: rsa
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    aws_session_token: '{{ aws_session_token }}'
  register: ec2_key_result

- name: Salvando a chave de acesso SSH localmente
  copy: content='{{ ec2_key_result.key.private_key }}' dest='{{ repo_keypair }}' mode=0600
  when: ec2_key_result.changed