- name: Iniciando Conexão com Amazon Web Services
  hosts: localhost
  vars_files:
  - vars/main.yaml

  roles:
    - create-modules
    - create-instance
    - describe-instance

- name: Iniciando conexão com a máquina EC2 Containernet
  hosts: instance-containernet
  become: true
  vars_files:
  - vars/main.yaml

  roles:
    - instance-configuration